name: Scheduled KML Extraction

on:
  schedule:
    # Runs at the start of every hour
    #- cron: '0 * * * *'
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures history is fully fetched

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install -y texlive-xetex

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run script
      run: |
        python extract_kml_info.py

    - name: Check if CSV changed
      id: csv_check
      run: |
        cd output
        LATEST_CSV=$(ls -Art firmas_*.csv | tail -n 1)
        git diff --exit-code $LATEST_CSV
        if [ $? -eq 1 ]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi

    - name: Commit and force push if changed
      if: steps.csv_check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Navigate to the output directory
        cd output
        
        # Assuming new files have already been generated by the script in the output directory:
        # First, remove any tracked files in the repository within the output directory
        git rm -rf --cached ./*

        # Copy the generated HTML file into a text file.
        LATEST_HTML=$(ls -Art firmas_*.html | tail -n 1)
        TXT_FILENAME="latest.txt"
        cp "${LATEST_HTML}" "${TXT_FILENAME}"
        
        # Add the newly generated files to staging
        git add .
        
        # Commit the changes. This commit will include the removal of old files and addition of new ones
        git commit -m "Update output files with latest run"
        
        # Navigate back to the root of the repository
        cd ..
        
        # Force push to overwrite history on the current branch
        git push origin HEAD:main --force
